branch-defaults:
  default:
    environment: new-simian-env
  master:
    environment: simian-api
    group_suffix: null
environment-defaults:
  new-simian-env:
    branch: master
    repository: origin
  simian-api:
    branch: null
    repository: null
  simian-app:
    branch: null
    repository: null
global:
  application_name: simian-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
